// <auto-generated />
using System;
using InventoryService.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryService.Api.Infrastructure.InventoryDbMigrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260503133031_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryService.Api.Domain.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("InventoryService.Api.Domain.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("InventoryService.Api.Domain.ReservationItem", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ReservationId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ReservationItems", t =>
                        {
                            t.HasCheckConstraint("CK_StockItem_Quantity_GE_Zero", "[Quantity] >= 0");
                        });
                });

            modelBuilder.Entity("InventoryService.Api.Domain.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuantityVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StockItems", t =>
                        {
                            t.HasCheckConstraint("CK_StockItem_AvailableQuantity_GE_Zero", "[AvailableQuantity] >= 0");

                            t.HasCheckConstraint("CK_StockItem_AvailableQuantity_LE_TotalQuantity", "[AvailableQuantity] <= [TotalQuantity]");

                            t.HasCheckConstraint("CK_StockItem_TotalQuantity_GE_Zero", "[TotalQuantity] >= 0");
                        });
                });

            modelBuilder.Entity("InventoryService.Api.Domain.ReservationItem", b =>
                {
                    b.HasOne("InventoryService.Api.Domain.Reservation", "Reservation")
                        .WithMany("Items")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("InventoryService.Api.Domain.Reservation", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
