version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: inventory-mssql
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1487:1433"
    #volumes:
    #  - mssql-data:/var/opt/mssql
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
  webapi:
    build:
      context: .
      dockerfile: InventoryService.Api/Dockerfile
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ConnectionStrings__InventoryDb": "Server=mssql,1433;Database=InventoryServiceDb;User Id=sa;Password=YourStrong!Passw0rd;Encrypt=False;TrustServerCertificate=True;"
      "ReservationCleanup__ReservationTtl": "00:15:00"
      "ReservationCleanup__PollingInterval": "00:00:30"
      "ReservationCleanup__BatchSize": "100"
      ASPNETCORE_URLS: http://+:80
    ports:
      - "1497:80"
#volumes:
#  mssql-data:

